version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - dev-network
    ports:
      - "8000:8000"

  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - dev-network
    ports:
      - "127.0.0.1:5432:5432"   # Ensure that it matches the port in the .env file

networks:
  dev-network:

volumes:
  postgres-data:
