version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspace
    command: sleep infinity   # Keep the container running 
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - dev-network
    ports:
      - "8000:8000"

  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - dev-network
    ports:
      - "127.0.0.1:5432:5432"   # Ensure that it matches the port in the .env file

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - dev-network
    ports:
      - "127.0.0.1:6379:6379"  # Ensure that it matches the port in the .env file
networks:
  dev-network:

volumes:
  postgres-data:
  redis-data: